"""Create payment table

Revision ID: 2185036a05a6
Revises: a078a06707bc
Create Date: 2021-04-04 20:16:44.734870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2185036a05a6'
down_revision = 'a078a06707bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_ref'), 'payments', ['ref'], unique=False)
    op.create_table('payment_extra_infos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_extra_infos')
    op.drop_index(op.f('ix_payments_ref'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
