name: Linter
on: push
jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2
      - name: Install Project Deps
        run: poetry install
      - name: Flake8 Check
        run: poetry run flake8 src/
      - name: Black Check
        run: poetry run black --check src/
      - name: Mypy Check
        run: poetry run mypy --config-file pyproject.toml src/