name: Testing
on: push
jobs:
  lint:
    name: Test the Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2
      - name: Install Project Deps
        run: poetry install
      - name: Run Tests
        run: poetry run pytest --cov=src --cov-fail-under=90 tests/